---
- name: CSR Router Configuration
  hosts: csr
  connection: network_cli
  gather_facts: no
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  tasks:
    - name: Configure loopback interface
      ios_config:
        parents:
          - interface Loopback14
        lines:
          - description Configured via Ansible - Thiago Torres - CICD Pipeline
          - ip address 10.10.10.14 255.255.255.255
