---
- name: CSR Router Configuration
  hosts: csr
  gather_facts: no
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

  tasks:
    - name: Configure loopback interface
      ios_config:
        lines:
          - interface Loopback0
          - ip address 10.10.10.1 255.255.255.0
