---

- name: IOSXE Router Configuration
  hosts: iosxe
  connection: network_cli
  gather_facts: no
  tasks:
    - name: Configure loopback interface 
      ios_config:
        parents:
          - interface Loopback10
        lines:
          - description Configured via Ansible - Thiago Torres - CICD Pipeline
          - ip address 10.10.10.100 255.255.255.255
